### ISSUE TITLE
Error message: You have entered an invalid date. [Required format: date=YYYY-MM-DD]

### ISSUE THREAD

**Issue by mhasanbulli** [evanodell/fixerapi#1]
Hello,

This error comes up when `fixer_historical()` function is called. Following is a simple example that can produce this error.
```
library(fixerapi)

Sys.setenv(FIXER_API_KEY = "<API_Key>")
fixer_historical(date = "2018-05-18")
```

The reason behind this error is the `ifelse()` function in `fixer_historical()`. By default, `ifelse()` strips all of the attributes of its variables. For example,
```
> ifelse(is.null(NULL), as.Date("2018-01-01"), 0)
[1] 17532
```
One way to resolve is to restore the `class()` of the original variable. Or, you can simply pass the `date` variable in with `as.character()`.

I can do a pull request for this if you like. 

Cheers.

**Comment by evanodell** [comment]
Thanks for flagging this, fixed in 403bcca.
